### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by mgrauer**

### CODE REVIEW

**Comment by mgrauer** [comment]
@cjh1 @kotfic @jbeezley 

I just cleaned up this branch and force pushed.  I've added Travis caching for pip and Girder's node_modules dir.

At the start of this testing, I saw build times of 

    Push: 13:27
    PR: 14:10

At the end I saw

    Push: 3:53
    PR: 6:08

That last PR (6:08, which is gone b/c of my force push) failed to upload the cache in 180 seconds at the end--I'm not sure if that is included in the build time, my guess is that it is not.

We may be able to tune this a bit further with caching the global npm install, the install of R, and tuning the caching a bit, but the first order of magnitude work is done.  

Unless this introduces anything that scares anyone, I'd say this is an improvement towards #40 .

**Comment by jbeezley** [comment]
Oh wow, I didn't know that travis allowed caching like that on the free accounts.  Anyway, LGTM.

**Comment by mgrauer** [comment]
Only on containerized builds for public projects.  And maybe that is new?

**Comment by cjh1** [comment]
I think you can do just:

cache: pip

Rather explicitly specifying the directory?

**Comment by cjh1** [comment]
I guess not if you have overridden the install step ...

**Comment by mgrauer** [comment]
@cjh1 yes, not if you override install step http://docs.travis-ci.com/user/caching/#pip-cache

I may just need to cache the pip cache dir and not site-packages, I'll explore that on some other PR.

**Pull request merged**
