### PR TITLE
Add first minerva client side test

### PR DESCRIPTION
**Pull request by mgrauer**

### CODE REVIEW

**Comment by mgrauer** [comment]
And they work!  Ready for review.

**Comment by kotfic** [comment]
@mgrauer  if you get a chance today can you walk me through this?  I am still a novice when it comes to javascript testing frameworks,  grunt,  and cmake.

**Comment by jbeezley** [comment]
I'm getting two test failures that may or may not by related to this branch:

```
test 102
      Start 102: server_minerva.contour_analysis

102: Test command: /Users/jbeezley/.pyenv/shims/coverage "run" "-p" "--append" "--rcfile=/Users/jbeezley/git/girder1/build/tests/girder.coveragerc" "--source=girder,/Users/jbeezley/git/girder1/clients/python/girder_client,/Users/jbeezley/git/girder1/plugins/minerva/server" "-m" "unittest" "-v" "plugin_tests.contour_analysis_test"
102: Environment variables:
102:  PYTHONPATH=:/Users/jbeezley/git/girder1/plugins/minerva:/Users/jbeezley/git/girder1/clients/python
102:  GIRDER_TEST_DB=mongodb://localhost:27017/girder_test_server_minerva_contour_analysis
102:  GIRDER_TEST_ASSETSTORE=server_minerva.contour_analysis
102:  GIRDER_TEST_PORT=20202
102: Test timeout computed to be: 1500
102: [06/Aug/2015:09:14:06] ENGINE Bus STARTING
102: [06/Aug/2015:09:14:06] ENGINE Started monitor thread '_TimeoutMonitor'.
102: [06/Aug/2015:09:14:06] ENGINE Started monitor thread 'Autoreloader'.
102: [06/Aug/2015:09:14:06] ENGINE Serving on http://0.0.0.0:20202
102: [06/Aug/2015:09:14:06] ENGINE Bus STARTED
102: testContourAnalysis (plugin_tests.contour_analysis_test.ContourAnalysesTestCase) ... ERROR
102: Exception in thread Thread-105:
102: Traceback (most recent call last):
102:   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
102:     self.run()
102:   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
102:     self.__target(*self.__args, **self.__kwargs)
102:   File "tests/mock_smtp.py", line 74, in loop
102:     asyncore.loop(timeout=0.5, use_poll=True)
102:   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
102:     poll_fun(timeout, map)
102:   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 145, in poll
102:     r, w, e = select.select(r, w, e, timeout)
102: error: (9, 'Bad file descriptor')
102:
102:
102: ======================================================================
102: ERROR: testContourAnalysis (plugin_tests.contour_analysis_test.ContourAnalysesTestCase)
102: ----------------------------------------------------------------------
102: Traceback (most recent call last):
102:   File "/Users/jbeezley/git/girder1/plugins/minerva/plugin_tests/contour_analysis_test.py", line 149, in setUp
102:     self.assertEqual(len(response.json), 1, 'Excepting only a single item')
102: AssertionError: Excepting only a single item
102:
102: ----------------------------------------------------------------------
102: Ran 1 test in 2.895s
102:
102: FAILED (errors=1)
102: Connected to MongoDB: mongodb://localhost:27017/girder_test_server_minerva_contour_analysis
102: Resolving plugin dependencies...
102: Loaded plugin "romanesco"
102: Loaded plugin "gravatar"
102: Loaded plugin "jobs"
102: Loaded plugin "minerva"
102: Started asynchronous event manager thread.
 7/16 Test #102: server_minerva.contour_analysis ...***Failed    3.40 sec
```
and
```
test 111
      Start 111: web_client_minerva

111: Test command: /Users/jbeezley/.pyenv/shims/python2.7 "-m" "unittest" "-v" "tests.web_client_test"
111: Environment variables:
111:  SPEC_FILE=/Users/jbeezley/git/girder1/plugins/minerva/plugin_tests/minervaSpec.js
111:  ASSETSTORE_TYPE=filesystem
111:  WEB_SECURITY=true
111:  ENABLED_PLUGINS=
111:  GIRDER_TEST_DB=mongodb://localhost:27017/girder_test_web_client_minerva
111:  GIRDER_TEST_ASSETSTORE=webclient_web_client_minerva
111:  GIRDER_PORT=30019
111:  BASEURL=/static/built/testEnvMinerva.html
111:  COVERAGE_FILE=/Users/jbeezley/git/girder1/build/js_coverage/minerva.cvg
111: Test timeout computed to be: 1500
111: [06/Aug/2015:09:14:12] ENGINE Bus STARTING
111: [06/Aug/2015:09:14:12] ENGINE Started monitor thread '_TimeoutMonitor'.
111: [06/Aug/2015:09:14:12] ENGINE Started monitor thread 'Autoreloader'.
111: [06/Aug/2015:09:14:12] ENGINE Serving on http://0.0.0.0:30019
111: [06/Aug/2015:09:14:12] ENGINE Bus STARTED
111: Connected to MongoDB: mongodb://localhost:27017/girder_test_web_client_minerva
111: Resolving plugin dependencies...
111: Started asynchronous event manager thread.
111: internal/child_process.js:274
111:   var err = this._handle.spawn(options);
111:                          ^
111: TypeError: Bad argument
111:     at TypeError (native)
111:     at ChildProcess.spawn (internal/child_process.js:274:26)
111:     at exports.spawn (child_process.js:333:9)
111:     at Object.<anonymous> (/Users/jbeezley/git/girder1/node_modules/phantomjs/bin/phantomjs:22:10)
111:     at Module._compile (module.js:430:26)
111:     at Object.Module._extensions..js (module.js:448:10)
111:     at Module.load (module.js:355:32)
111:     at Function.Module._load (module.js:310:12)
111:     at Function.Module.runMain (module.js:471:10)
111:     at startup (node.js:117:18)
111: testWebClientSpec (tests.web_client_test.WebClientTestCase) ... Retrying test
111: internal/child_process.js:274
111:   var err = this._handle.spawn(options);
111:                          ^
111: TypeError: Bad argument
111:     at TypeError (native)
111:     at ChildProcess.spawn (internal/child_process.js:274:26)
111:     at exports.spawn (child_process.js:333:9)
111:     at Object.<anonymous> (/Users/jbeezley/git/girder1/node_modules/phantomjs/bin/phantomjs:22:10)
111:     at Module._compile (module.js:430:26)
111:     at Object.Module._extensions..js (module.js:448:10)
111:     at Module.load (module.js:355:32)
111:     at Function.Module._load (module.js:310:12)
111:     at Function.Module.runMain (module.js:471:10)
111:     at startup (node.js:117:18)
111: Retrying test
111: internal/child_process.js:274
111:   var err = this._handle.spawn(options);
111:                          ^
111: TypeError: Bad argument
111:     at TypeError (native)
111:     at ChildProcess.spawn (internal/child_process.js:274:26)
111:     at exports.spawn (child_process.js:333:9)
111:     at Object.<anonymous> (/Users/jbeezley/git/girder1/node_modules/phantomjs/bin/phantomjs:22:10)
111:     at Module._compile (module.js:430:26)
111:     at Object.Module._extensions..js (module.js:448:10)
111:     at Module.load (module.js:355:32)
111:     at Function.Module._load (module.js:310:12)
111:     at Function.Module.runMain (module.js:471:10)
111:     at startup (node.js:117:18)
111: Retrying test
111: internal/child_process.js:274
111:   var err = this._handle.spawn(options);
111:                          ^
111: TypeError: Bad argument
111:     at TypeError (native)
111:     at ChildProcess.spawn (internal/child_process.js:274:26)
111:     at exports.spawn (child_process.js:333:9)
111:     at Object.<anonymous> (/Users/jbeezley/git/girder1/node_modules/phantomjs/bin/phantomjs:22:10)
111:     at Module._compile (module.js:430:26)
111:     at Object.Module._extensions..js (module.js:448:10)
111:     at Module.load (module.js:355:32)
111:     at Function.Module._load (module.js:310:12)
111:     at Function.Module.runMain (module.js:471:10)
111:     at startup (node.js:117:18)
111: Retrying test
111: internal/child_process.js:274
111:   var err = this._handle.spawn(options);
111:                          ^
111: TypeError: Bad argument
111:     at TypeError (native)
111:     at ChildProcess.spawn (internal/child_process.js:274:26)
111:     at exports.spawn (child_process.js:333:9)
111:     at Object.<anonymous> (/Users/jbeezley/git/girder1/node_modules/phantomjs/bin/phantomjs:22:10)
111:     at Module._compile (module.js:430:26)
111:     at Object.Module._extensions..js (module.js:448:10)
111:     at Module.load (module.js:355:32)
111:     at Function.Module._load (module.js:310:12)
111:     at Function.Module.runMain (module.js:471:10)
111:     at startup (node.js:117:18)
111: Retrying test
111: FAIL
111: Exception in thread Thread-105:
111: Traceback (most recent call last):
111:   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
111:     self.run()
111:   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
111:     self.__target(*self.__args, **self.__kwargs)
111:   File "tests/mock_smtp.py", line 74, in loop
111:     asyncore.loop(timeout=0.5, use_poll=True)
111:   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
111:     poll_fun(timeout, map)
111:   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 145, in poll
111:     r, w, e = select.select(r, w, e, timeout)
111: error: (9, 'Bad file descriptor')
111:
111:
111: ======================================================================
111: FAIL: testWebClientSpec (tests.web_client_test.WebClientTestCase)
111: ----------------------------------------------------------------------
111: Traceback (most recent call last):
111:   File "tests/web_client_test.py", line 188, in testWebClientSpec
111:     self.assertEqual(returncode, 0)
111: AssertionError: 1 != 0
111:
111: ----------------------------------------------------------------------
111: Ran 1 test in 9.819s
111:
111: FAILED (failures=1)
16/16 Test #111: web_client_minerva ................***Failed   10.18 sec
```
Any ideas?

**Comment by jbeezley** [comment]
I'm also getting a number of failures from the girder test suite as well.  I'm in the process of submitting a report to cdash.  I'll link it when it is done.

**Comment by jbeezley** [comment]
Welp, `ctest -D Experimental` failed to submit to cdash.  Anyway, all of the client tests failed, so clearly there is something wrong with my setup.

**Comment by mgrauer** [comment]
I should mention that this relies on a cutting edge master of Girder, changes merged in just yesterday are required for this to work.  Travis is OK because it checks out the latest master of Girder.

@kotfic I can walk you through this today.  @jbeezley let me know if you want to be a part of that or want to talk about it otherwise.

**Comment by jbeezley** [comment]
Okay, my phantomjs install was broken.  Everything works now.

LGTM

**Pull request merged**
