### PR TITLE
Add support for importing an S3 bucket as a dataset

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@mgrauer This is ready for review

**Comment by mgrauer** [comment]
can you add the jobs plugin as a dependency in plugin.json?

**Comment by mgrauer** [comment]
I've merged master and pushed that commit.

Is it possible to add server side tests here?  If not, at least the current tests should pass.

**Comment by cjh1** [comment]
@mgrauer Added a testcase ( and fix a bug it revealed! )

**Comment by mgrauer** [comment]
Thanks @cjh1 .  Hooray for testing!

**Pull request merged**
