### PR TITLE
Add iso-contour analysis

### PR DESCRIPTION
**Pull request by cjh1**
This analysis takes a file id for a NetCDF file and converts the file
into a format that can be rendered as an iso-contour layer in GeoJs.
Currently we only convert a small section of the file, so it can be
rendered on the client side.

### CODE REVIEW

**Comment by cjh1** [comment]
@mgrauer This is our first real analysis for NEX, I have it running in romanesco

**Comment by aashish24** [comment]
Yay!!

**Comment by cjh1** [comment]
@mgrauer This is ready for review now

**Comment by mgrauer** [comment]
LGTM

**Pull request merged**
