### PR TITLE
Removing romanesco's R dependency

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@mgrauer This removes our R dependency ... using the new romanesco plugin system.

**Comment by mgrauer** [comment]
I'm not sure if this is what you mean, but you can go to a Travis build, then go to settings menu/caches, and delete a cache from Travis.  My understanding is that it will clear out the cached files as they currently stand, and then re-cache the requested folders after the next run.

**Comment by cjh1** [comment]
Yep, that is what I was trying todo by removing the cache statements, I am guessing it did a similar thing ...

**Comment by mgrauer** [comment]
Build times are super fast now.  LGTM.

**Pull request merged**
